name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
      - name: Check fmt
        run: deno fmt --check
      - name: Run lint
        run: deno lint
      - name: Run type check
        run: deno cache *.ts

